### ISSUE TITLE
Enhance Colour Palette for Improved Detail

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/ASCII-Camera#1]
Currently the colours are being added using ANSI color codes making our ranges very limited. Try to add more colours to get a more detailed impression of the frame.

 tl;dr  Add more colours!!!!!!

**Comment by Hiyanachnani** [comment]
hiii please assign this to me

**Comment by Vaarun-C** [comment]
Sure thing all the best :)

**Comment by kavs2803** [comment]
heyy can i be assigned this issue

**Comment by Suhaniverma2004** [comment]
hey can i be assigned to this issue

**Comment by Vaarun-C** [comment]
Someone is working on this already... feel free to chose others :)

**Comment by DedLad** [comment]
atleast this???

**Comment by LalithaTanmayee** [comment]
can you assign this to me pls
