### ISSUE TITLE
Optimizing rendering for improved performance

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/ASCII-Camera#3]
The current implementation matches each pixel value in the webcam feed to an ASCII character. Which is computationally expensive, especially for high-definition webcams. Try to enhance performance by sacrificing some quality

This might also fix the terminal resizing issue.

Hint: You can try pixelization

**Comment by bwaklog** [comment]
Can I be assigned this issue?

**Comment by Vaarun-C** [comment]
Sure, Good Luck!

**Comment by karun1763** [comment]
can i be assigned

**Comment by Vaarun-C** [comment]
@bwaklog can you show me some progress by 10:15?

or I'll close this issue and you can work on other repos :)

**Comment by bwaklog** [comment]
I have a faster version, but its slightly cropped, im pushing it now

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by bwaklog** [comment]
There seems to be an issue with the colours and pixelation. You can go ahead and close the issue. Ill try working on it again some other time

**Comment by Vaarun-C** [comment]
> can i get assigned if this is still open?

this was actually solved but @bwaklog wanted to improve the solution.
