### ISSUE TITLE
Add a Helpful Menu

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/ASCII-Camera#5]
Here's what I have in mind:
- When you launch the application, it should display a friendly menu with instructions.
- A quick overview of any keybindings, like the "Q," "W," "S," and "V" keys, could be a nice touch.

PS: See #4

**Comment by Thatboringguy** [comment]
can i be assigned this issue

**Comment by Vaarun-C** [comment]
One issue at a time...

**Comment by Rishav1git** [comment]
can u assign this issue to me

**Comment by Vaarun-C** [comment]
Sure thing all the best :)

**Comment by srijan-nodes** [comment]
can I get this please?

**Comment by Chatter-77** [comment]
Can i get assigned to this issue?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by DedLad** [comment]
lettt meee dooo thisss

**Comment by SmritiMallya** [comment]
can I get assigned?

**Comment by Vaarun-C** [comment]
> can u assign this issue to me

are you still working on this? @Rishav1git

**Comment by Vaarun-C** [comment]
> can I get this please?

go ahead @srijan-nodes

**Comment by amankhandelwaal** [comment]
Hey, there seem to be no issue #4

**Comment by N0Xl0US** [comment]
issue pls

**Comment by Vaarun-C** [comment]
> Hey, there seem to be no issue #4

yep that was closed as someone fixed it :)

**Comment by Vaarun-C** [comment]
@srijan-nodes can you show me some progress by 10:15

**Comment by srijan-nodes** [comment]
i didn't see the tag...will show by 10:30...is that okay?

**Comment by Alley2717** [comment]
can i try

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by Lalith2907** [comment]
can i get assigned to this?
