### ISSUE TITLE
Add Keybinds ['W', 'Q']

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/ASCII-Camera#6]
Add some simple key bindings? Here's what I have in mind:

- **W:** Start the Webcam
- **Q:** Stop the Webcam

I think these key bindings would be super cool :)

**Comment by Thatboringguy** [comment]
can i be assigned this issue

**Comment by Vaarun-C** [comment]
Sure thing man :) All the best

**Comment by Vaarun-C** [comment]
PLEASE SEE: There's a for loop which limits it to 10 frames. Please switch that out for `while True:` to enable forever.

**Comment by Rishav1git** [comment]
can u assign issue to me

**Comment by Vaarun-C** [comment]
someone is already working on this one. Feel free to chose others :)

**Comment by srijan-nodes** [comment]
can  I get this issue

**Comment by Vaarun-C** [comment]
> can I get this issue

Someone is already working on this issue... feel free to chose others :)

**Comment by DedLad** [comment]
maybe this??:)

**Comment by SafwanAhmed08** [comment]
can i get assigned to this

**Comment by Vaarun-C** [comment]
> can u assign issue to me

@Rishav1git you can go ahead

**Comment by 7Akshu77** [comment]
can I get assigned to this issue

**Comment by Vaarun-C** [comment]
> > can u assign issue to me
> 
> @Rishav1git you can go ahead

Can you show me some progress by 10:15? @Rishav1git

**Comment by Hiyanachnani** [comment]
hiii can i be assigned to this

**Comment by Lalith2907** [comment]
can i be assigned to this issue?

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by SafwanAhmed08** [comment]
can i get this??

**Comment by UdayaPragna** [comment]
could i be assinged this issue

**Comment by Vaarun-C** [comment]
@Rishav1git I'm reassigning this issue to someone else

**Comment by Vaarun-C** [comment]
@srijan-nodes go ahead

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by Vaarun-C** [comment]
> maybe this??:)

@DedLad go on

**Comment by 7Akshu77** [comment]
can you assign this issue to me
